base: &base
  adapter: postgres
  encoding: unicode

development:
  <<: *base
  database: rss_reader_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *base
  database: rss_reader_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *base
  database: rss_reader_production
  username: postgres
  password: postgres
  host: localhost
